### ISSUE TITLE
Create Navigation

### ISSUE THREAD

**Issue by eduardoccmelo** [eduardoccmelo/capstone-project#1]
## Value statement

As an user
I need to have a navigation system
so that I can navigate through the pages of the app

## Acceptance criteria

Create a navigation system for:
- "/"
- "/mytrips"
- "/mytrips/:id"
- "/mytrips/:id/edit
- "/worldmap"
- "/newtrip"

## Tasks

- [x] Create a static landing page
- [x] Create a static MY TRIPS page
- [x] Create a static MY TRIPS / :ID page
- [x] Create a static MY TRIPS / :D /  EDIT Page
- [x] Create a static WORLD MAP page
- [x] Create a static NEW TRIP page
- [x] Navigate through all the pages

## Size

Medium
