### ISSUE TITLE
Create WORLD MAP Page

### ISSUE THREAD

**Issue by eduardoccmelo** [eduardoccmelo/capstone-project#2]
## Value statement

As an user
I need to render a map and all the countries in the World
so that I can check every country that I visited already

## Acceptance criteria

Render a world map and a list of all the countries in the world. When a country is selected, its position is tagged on the map. A counter set how many countries were visited and the list of the countries can be filtered by name

## Tasks

- [x] Render a world map from Mapbox
- [x] Render a list of all the countries in the world (with coordinates)
- [x] Every checkbox checked pin the location of the selected country on the map
- [x] A counter set how many countries were visited
- [x] Countries can be filtered by name

## Size

Large
