### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by eduardoccmelo** [eduardoccmelo/capstone-project#3]
## Value statement

As an user
I need to have a landing page
so that I can navigate through the world map or my trips page

## Acceptance criteria

Create a simple landing page to give the possibility to navigate to the world map page or my trips page

## Tasks

- [ ] Create an icon linking to the world map page
- [ ] Create an icon linking to my trips page
- [ ] Create some animation for the icons

## Size

Small
