### ISSUE TITLE
Create MY TRIPS Page

### ISSUE THREAD

**Issue by eduardoccmelo** [eduardoccmelo/capstone-project#4]
## Value statement

As an user
I need to have a page with an overview of my travels
so that I can check all my planned travels and the dates of every trip

## Acceptance criteria

Create a page to see all the planned travels.

## Tasks

- [ ] Create a button to ADD a new travel
- [ ] Create a button to return to the landing page
- [ ] Create a static card with the title of the travel and its date
- [ ] Create a delete button to remove the trip

## Size

Small
