### ISSUE TITLE
Create MY TRIPS / :ID and Edit Pages

### ISSUE THREAD

**Issue by eduardoccmelo** [eduardoccmelo/capstone-project#5]
## Value statement

As an user
I need to have a detailed page
so that I can check all the information about my trip and edit it

## Acceptance criteria

Create a page to display all the information about a single trip

## Tasks

- [x] Set a basic css format
- [x] Get the data from Local Storage
- [x] Create a field for destination name and dates
- [x] Create a field for transport
- [x] Create a field for accommodation
- [x] Create a field for sightseeing
- [x] Create a button to return to the MY TRIPS Page
- [x]  Create a button to UPDATE the trip
- [x] Create a button to CANCEL the update and return to MY TRIPS / :ID Page
- [x] Open an edit form displaying the currently information of the form
- [x] Output the new form data

## Size

Medium
