### ISSUE TITLE
Create NEW TRIP

### ISSUE THREAD

**Issue by eduardoccmelo** [eduardoccmelo/capstone-project#6]
## Value statement

As an user
I need to have a page to add a new trip
so that I can fill all the information about a single travel

## Acceptance criteria

Create a form to receive all the information about the next travel

## Tasks

- [x] Create a button to CREATE the new trip
- [x] Create a button to CANCEL the new trip
- [x] Create a form to get the data
- [x] Output the data from the form
- [x] Use Local Storage to store data
- [x] Redirect to My trips page after submit
- [x] Create a button to ADD a new travel
- [x] Create a button to return to the landing page
- [x] Create a static card with the title of the travel and its date
- [x] Create a delete button to remove the trip
- [x] When the trip is clicked, redirect to the trip details page

## Size

Large
