### ISSUE TITLE
Create MY TRIPS / :ID / EDIT page

### ISSUE THREAD

**Issue by eduardoccmelo** [eduardoccmelo/capstone-project#7]
## Value statement

As an user
I need to have an edit page
so that I can change the data from my trip

## Acceptance criteria

Create a page to edit the data of the trip and update the currently data

## Tasks

- [ ] Create a button to UPDATE the trip
- [ ] Create a button to CANCEL the update and return to MY TRIPS / :ID Page
- [ ] Open an edit form displaying the currently information of the form
- [ ] Output the new form data

## Size

Medium
